name: gurmukhi_keyboard_settings
description: Settings app for Gurmukhi Keyboard
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - ../app/src/main/assets/gurbani/shabad-hazare/content.txt

  fonts:
    - family: Akhar
      fonts:
        - asset: ../app/src/main/assets/fonts/akhar.ttf
